spring.cloud.stream:
  kafka:
    streams:
      binder:
        brokers: localhost:9092
        configuration:
          commit.interval.ms: 1000
          default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          security.protocol: SASL_PLAINTEXT
          sasl.mechanism: PLAIN
  bindings:
    process-out-0:
      destination: english-counts
    process-out-1:
      destination: french-counts
    process-out-2:
      destination: spanish-counts
    process-in-0:
      destination: words

server.port: 8084
jaas:
  conf:
    password: ${PASSWORD_JAAS:admin-secret}
    user: ${USER_JAAS:admin}